FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# honmatest

ApiaryでのAPIドキュメントテストを書きます。

## Users Collection [/users]

### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "id": "9871236458757",
                "name": "Hitoshi Honma"
            }
        ]

### Create a User [POST]

+ Request (application/json)

        {
            "name": "Hitoshi Honma"
        }

+ Response 201 (application/json)

        {
            "id": "9871236458757",
            "name": "Hitoshi Honma"
        }
